# Generated by Django 5.1.6 on 2025-03-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_amount'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion'),
        ),
    ]
