# Generated by Django 5.1.6 on 2025-03-08 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='membership_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
