# Generated by Django 5.1.6 on 2025-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.TextField(default='General'),
        ),
    ]
