# Generated by Django 5.1.6 on 2025-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_activity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
