# Generated by Django 5.1.6 on 2025-03-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[(60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes'), (180, '180 minutes')], default=60, help_text='Duration in minutes'),
        ),
    ]
